### ISSUE TITLE
Update NPM

### ISSUE THREAD

**Issue by julian-martinez-del-campo** [steveadoo32/ngx-signalr-hubservice#10]
Would it be possible to update the NPM package to version 6.x?

Sidenote:

Installing through npm with the gitrepo (eg npm i --save https://github.com/steveadoo32/ngx-signalr-hubservice) to use the updated version causes error:

Module not found: Error: Can't resolve 'ngx-signalr-hubservice' in ...

I compared this version with npm package and looks like the actual source is missing?

![directories](https://user-images.githubusercontent.com/38327947/41937995-7232e09c-7957-11e8-988c-e4845f0a31f2.png)

**Comment by steveadoo32** [comment]
ngx-signalr-hubservice@6.0.2 should be the latest version. I just tested it and it is working.
