### ISSUE TITLE
how to get the hub connection id?

### ISSUE THREAD

**Issue by alagurajap1981** [steveadoo32/ngx-signalr-hubservice#4]
Thanks. The library looks solid to connect to a SignalR Hub. For some internal logging I need to fetch the client connection id? Is it possible to get the same?

**Comment by steveadoo32** [comment]
Hi,

I can expose the SignalR connection instance to you. I will update the library soon.

**Comment by steveadoo32** [comment]
Update to 1.1.4 and [checkout the new documentation](https://github.com/steveadoo32/ngx-signalr-hubservice#notes).

**Comment by alagurajap1981** [comment]
Thanks for the prompt response and resolving in no time. I appreciate.

Thanks & Regards,
Alagu
