### ISSUE TITLE
I wanted to add query string to the hub connection. Couldnt found a way out?

### ISSUE THREAD

**Issue by nik0405** [steveadoo32/ngx-signalr-hubservice#5]
I wanted something equivalent to [$.connection.hub.qs] which we set up while using jQuery.

Please Help!!

**Comment by steveadoo32** [comment]
Yes, I can implement this feature. Should have it done by the end of the week.

**Comment by nik0405** [comment]
Hi , did you try doing it?

I tried , but on first loginof my application if successfully works , but on refresh of page i am not able to send back the query string again , though the connection is trying to reconnect. 

   async connection() {
        if (!this.connected) {
            this.connected = await this.hubService.connect(this.url).toPromise();//environment.signalRURL
            this.hubService.connection.qs = { 'ClientId': this._auth.getUser().SystemUserId };
            this.hubWrapper = this.hubService.register(this);
        }
    }

**Comment by steveadoo32** [comment]
Sorry. Christmas time is busy for me. I will try to get to this some time this week.

**Comment by nik0405** [comment]
Thanks for the response , but i figured out a way .
i modified your library with an extra parameter in initConnection() method.

Thanks!!

**Comment by steveadoo32** [comment]
If  you are interested, I added a `qs` parameter to the `connect` method on `HubService`. This is in version 1.1.5.
