### ISSUE TITLE
Incompatible with rxjs 6.0.0

### ISSUE THREAD

**Issue by tolvaly** [steveadoo32/ngx-signalr-hubservice#7]
Could you fix the imports for rxjs 6.0.0 ?

rxjs changed the import strategy:

[v6.0.0-alpha.1 changelog](https://github.com/ReactiveX/RxJS/compare/5.5.3...v6.0.0-alpha.1)

> * creation functions: All create functions such as of, from, combineLatest and fromEvent should now be imported from rxjs/create.

> * operators: Pipeable operators must now be imported from rxjs like so: import { map, filter, switchMap } from 'rxjs/operators';. No deep imports.

> * deep imports: Can no longer deep import top-level types such as rxjs/Observable, rxjs/Subject, rxjs/ReplaySubject, et al. All imports should be done directly from rxjs, for example: import \{ Observable, Subject \} from 'rxjs';

I suggest to use version numbering used by rxjs in the future release

**Comment by steveadoo32** [comment]
Closed by #8
